version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: miso_soup_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miso_soup
    ports:
      - "3318:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - miso_soup_network

volumes:
  mysql_data:
    driver: local

networks:
  miso_soup_network:
    driver: bridge
